include(
    ":app",
    Modules.Account.data,
    Modules.Account.domain,
    Modules.Account.ui,
    Modules.Authentication.data,
    Modules.Authentication.domain,
    Modules.Authentication.ui,
    Modules.Core.data,
    Modules.Core.domain,
    Modules.Core.ui,
    Modules.Home.data,
    Modules.Home.domain,
    Modules.Home.ui,
    Modules.strings
)
