include(
    ":app",
    Deps.Project.Authentication.data,
    Deps.Project.Authentication.domain,
    Deps.Project.Authentication.ui,
    Deps.Project.Core.data,
    Deps.Project.Core.domain,
    Deps.Project.Core.ui,
    Deps.Project.strings
)
